@startuml
actor Bibliotecario as UA
participant Biblioteca as B
participant ServizioGestioneLibri as S
participant LibroRepository as R

UA -> B : inserisciLibro(datiLibro)
B -> S : inserisciLibro(datiLibro)
S -> R : salva(libro)
R --> S : ok
S --> B : conferma
B --> UA : libro inserito correttamente
@enduml
