@startuml
actor Bibliotecario as UA
participant Biblioteca as B
participant ServizioPrestiti as PS
participant PrestitoRepository as PR
participant LibroRepository as LR

UA -> B : registraRestituzione(prestito)
B -> PS : registraRestituzione(prestito)

PS -> PR : cercaPrestito(prestito)
PR --> PS : prestito

PS -> PR : eliminaPrestito(prestito)
PR --> PS : ok

PS -> LR : incrementaCopie(isbn)
LR --> PS : ok

PS --> B : restituzione confermata
B --> UA : libro restituito
@enduml
