@startuml
actor Bibliotecario as UA
participant Biblioteca as B
participant ServizioGestioneLibri as S
participant LibroRepository as R

UA -> B : inserisciLibro(Libro)
B -> S : inserisciLibro(libro)
S -> R : salva(libro)
R --> S : ok
S --> B : conferma
B --> UA : libro inserito correttamente
@enduml
