@startuml
actor Bibliotecario as OP
participant Biblioteca as B
participant ServizioGestioneUtenti as S
participant UtenteRepository as R

OP -> B : modificaUtente(matricola, nuoviDati)
B -> S : modificaUtente(...)
S -> R : cercaPerMatricola(matricola)
R --> S : utente
S -> R : aggiorna(utente)
R --> S : ok
S --> B : modifica completata
B --> OP : conferma modifica
@enduml
