@startuml
actor Bibliotecario as OP
participant Biblioteca as B
participant ServizioGestioneUtenti as S
participant UtenteRepository as R

OP -> B : cercaUtente(cognome | matricola)
B -> S : cercaUtente(...)
S -> R : cerca(...)
R --> S : risultati
S --> B : lista utenti trovati
B --> OP : visualizza utenti trovati
@enduml
